# Generated by Django 3.2.6 on 2022-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('capacity', models.CharField(max_length=1000)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
