# Generated by Django 3.0.2 on 2020-10-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetvis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gencloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_wordcloud', models.ImageField(default='avatar-1.png', upload_to='analysis')),
            ],
        ),
    ]
